# Generated by Django 4.0 on 2021-12-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='faculty_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='faculty code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roll_no',
            field=models.CharField(blank=True, max_length=12, verbose_name='roll number'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='material',
            field=models.FileField(upload_to='resources/%Y/%m/%d/%H-%M-%S'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='notifications/%Y/%m/%d/%H-%M-%S')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('doubt', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='doubts/%Y/%m/%d/%H-%M-%S')),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_by', to='link_app.customuser')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='link_app.customuser')),
            ],
        ),
    ]
