# Generated by Django 4.0 on 2021-12-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0002_customuser_faculty_code_customuser_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notifications/%Y/%m/%d/%H-%M-%S'),
        ),
    ]
