# Generated by Django 4.0 on 2021-12-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0003_alter_notification_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doubt',
        ),
    ]
