# Generated by Django 4.0 on 2021-12-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0004_delete_doubt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('doubt', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='doubts/%Y/%m/%d/%H-%M-%S')),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_by', to='link_app.customuser')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='link_app.customuser')),
            ],
        ),
    ]
