# Generated by Django 4.0 on 2021-12-23 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0006_doubt_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soulution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='solutions/%Y/%m/%d/%H-%M-%S')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link_app.doubt')),
            ],
        ),
    ]
