# Generated by Django 4.0 on 2021-12-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0007_soulution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Soulution',
            new_name='Solution',
        ),
    ]
